.TH "Desktop/Projeto_easy/src Directory Reference" 3 "Fri Jun 2 2017" "Controle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Desktop/Projeto_easy/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBControle\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDetector\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
