.TH "Desktop/Projeto_easy/include Directory Reference" 3 "Sat Jun 3 2017" "Controle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Desktop/Projeto_easy/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBControle\&.h\fP"
.br
.ti -1c
.RI "file \fBDetector\&.h\fP"
.br
.ti -1c
.RI "file \fBSocket\&.h\fP"
.br
.in -1c
