.TH "Desktop/Projeto_easy/src/Controle.cpp" 3 "Fri Jun 2 2017" "Controle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Desktop/Projeto_easy/src/Controle.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/Controle\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Controle from the source code\&.
