.TH "Desktop/Projeto_easy/include/Controle.h" 3 "Wed Jun 7 2017" "Controle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Desktop/Projeto_easy/include/Controle.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&./Detector\&.h'\fP
.br
\fC#include '\&./Socket\&.h'\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <thread>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBControle\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Controle from the source code\&.
