.TH "Desktop/Projeto_easy/include/Detector.h" 3 "Sat Jun 3 2017" "Controle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Desktop/Projeto_easy/include/Detector.h
.SH SYNOPSIS
.br
.PP
\fC#include 'opencv2/objdetect\&.hpp'\fP
.br
\fC#include 'opencv2/highgui\&.hpp'\fP
.br
\fC#include 'opencv2/imgproc\&.hpp'\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDetector\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Controle from the source code\&.
