.TH "Desktop/Projeto_easy/include/Detector.h" 3 "Wed Jun 7 2017" "Controle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Desktop/Projeto_easy/include/Detector.h
.SH SYNOPSIS
.br
.PP
\fC#include 'opencv2/objdetect\&.hpp'\fP
.br
\fC#include 'opencv2/highgui\&.hpp'\fP
.br
\fC#include 'opencv2/imgproc\&.hpp'\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <dlib/opencv\&.h>\fP
.br
\fC#include <dlib/image_processing/frontal_face_detector\&.h>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <dlib/image_processing/render_face_detections\&.h>\fP
.br
\fC#include <dlib/image_processing\&.h>\fP
.br
\fC#include <dlib/gui_widgets\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDetector\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNEXTCANAL\fP   1"
.br
.ti -1c
.RI "#define \fBPREVCANAL\fP   2"
.br
.ti -1c
.RI "#define \fBMAISVOLUME\fP   3"
.br
.ti -1c
.RI "#define \fBMENOSVOLUME\fP   4"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAISVOLUME   3"

.PP
Definition at line 16 of file Detector\&.h\&.
.SS "#define MENOSVOLUME   4"

.PP
Definition at line 17 of file Detector\&.h\&.
.SS "#define NEXTCANAL   1"

.PP
Definition at line 14 of file Detector\&.h\&.
.SS "#define PREVCANAL   2"

.PP
Definition at line 15 of file Detector\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Controle from the source code\&.
