.TH "server" 3 "Wed Jun 7 2017" "Controle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBs\fP = socket\&.socket(socket\&.AF_INET, socket\&.SOCK_STREAM)"
.br
.ti -1c
.RI "\fBcsocket\fP"
.br
.ti -1c
.RI "\fBaddress\fP"
.br
.ti -1c
.RI "\fBdata\fP = csocket\&.recv(1)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "server\&.address"

.PP
Definition at line 8 of file server\&.py\&.
.SS "server\&.csocket"

.PP
Definition at line 8 of file server\&.py\&.
.SS "server\&.data = csocket\&.recv(1)"

.PP
Definition at line 10 of file server\&.py\&.
.SS "server\&.s = socket\&.socket(socket\&.AF_INET, socket\&.SOCK_STREAM)"

.PP
Definition at line 4 of file server\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Controle from the source code\&.
