.TH "Desktop/Projeto_easy/server.py" 3 "Wed Jun 7 2017" "Controle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Desktop/Projeto_easy/server.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBserver\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBserver\&.s\fP = socket\&.socket(socket\&.AF_INET, socket\&.SOCK_STREAM)"
.br
.ti -1c
.RI "\fBserver\&.csocket\fP"
.br
.ti -1c
.RI "\fBserver\&.address\fP"
.br
.ti -1c
.RI "\fBserver\&.data\fP = csocket\&.recv(1)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Controle from the source code\&.
