.TH "Desktop/Projeto_easy/include/Socket.h" 3 "Wed Jun 7 2017" "Controle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Desktop/Projeto_easy/include/Socket.h
.SH SYNOPSIS
.br
.PP
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'unistd\&.h'\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSocket\fP"
.br
.ti -1c
.RI "class \fBSocketCliente\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUFFERSIZE\fP   124"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFERSIZE   124"

.PP
Definition at line 11 of file Socket\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Controle from the source code\&.
